name: Release

on:
  push:
    tags:
      - v*


jobs:
  image:
    name: Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=${GITHUB_REF:11}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Login GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traptitech
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/traptitech/game3/wordpress:${{ env.IMAGE_TAG }}
            ghcr.io/traptitech/game3/wordpress:latest